backend:
  name: github
  repo: nixxholas/nixxholas.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

# Uncomment below for local development
# local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # Blog Posts Collection
  - name: "blog"
    label: "Blog Posts"
    folder: "content"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishedAt", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
